### ISSUE TITLE
Possible to override default subdomain checks?

### ISSUE THREAD

**Issue by renzor-fist** [LayeredStudio/dns-records#43]
Hello, I noticed this line in the `getAllDnsRecordsStream` function which seems to automatically check a long list of subdomains that I want to avoid in order to avoid unnecessary calls to improve performance. Is there a way to do this?
```
const subdomainsExtra = [...subdomainsRecords];
```

**Comment by AndreiIgna** [comment]
hey @renzor-fist this sounds like it could be an option for `getAllDnsRecordsStream()`, to skip checking the subdomains list. Will be added in next release

**Comment by AndreiIgna** [comment]
from `v2.1` onwards, you can use the `commonSubdomainsCheck` option

```js
const stream = getAllDnsRecordsStream('example.com', {
  commonSubdomainsCheck: false
})
```
